/**
 * SuperRAG mock data layer.
 *
 * This project is plain HTML/CSS/JS for now, so the shared mock dataset is
 * exposed on window.SuperRagMock. Future real API integration should keep
 * these field names stable and replace only api.js.
 */
(function () {
  const mockStats = {
    documentCount: 5,
    categoryCount: 5,
    todayQuestionCount: 18,
    designOutputCount: 8,
    indexingCount: 1,
    failedDocumentCount: 0,
  };

  const mockDocuments = [
    {
      id: "doc-001",
      title: "01_CRM客户管理模块说明.md",
      type: "Markdown",
      project: "SuperRAG CRM 演示库",
      tags: ["CRM", "客户", "需求", "业务规则"],
      uploader: "系统预置",
      version: "v1.0",
      status: "indexed",
      visibilityScope: "项目成员",
      updatedAt: "2026-05-31 12:20",
      summary: "覆盖客户新建、客户场景、查找筛选、负责人转移、公海池、团队成员协作、跟进记录和客户任务。",
      keywords: ["客户", "负责人", "公海池", "团队成员", "跟进记录", "客户任务"],
      difyDatasetId: "ds_superrag_crm_demo",
      difyDocumentId: "crm_customer_doc",
      scene: "通用",
    },
    {
      id: "doc-002",
      title: "02_CRM商机管理模块说明.md",
      type: "Markdown",
      project: "SuperRAG CRM 演示库",
      tags: ["CRM", "商机", "阶段流转", "金额计算"],
      uploader: "系统预置",
      version: "v1.0",
      status: "indexed",
      visibilityScope: "项目成员",
      updatedAt: "2026-05-31 12:21",
      summary: "覆盖商机新建、客户关联、产品与金额计算、商机场景、阶段推进、赢单输单和销售漏斗。",
      keywords: ["商机", "客户", "产品", "金额", "阶段", "赢单", "输单"],
      difyDatasetId: "ds_superrag_crm_demo",
      difyDocumentId: "crm_opportunity_doc",
      scene: "design",
    },
    {
      id: "doc-003",
      title: "03_CRM合同管理模块说明.md",
      type: "Markdown",
      project: "SuperRAG CRM 演示库",
      tags: ["CRM", "合同", "合同编号", "财务联动"],
      uploader: "系统预置",
      version: "v1.0",
      status: "indexed",
      visibilityScope: "项目成员",
      updatedAt: "2026-05-31 12:22",
      summary: "覆盖合同新建、合同编号生成、客户与商机关联、产品同步、回款发票联动和合同权限协作。",
      keywords: ["合同", "合同编号", "客户", "商机", "回款", "发票"],
      difyDatasetId: "ds_superrag_crm_demo",
      difyDocumentId: "crm_contract_doc",
      scene: "handover",
    },
    {
      id: "doc-004",
      title: "04_CRM回款管理模块说明.md",
      type: "Markdown",
      project: "SuperRAG CRM 演示库",
      tags: ["CRM", "回款", "合同回款", "金额校验"],
      uploader: "系统预置",
      version: "v1.0",
      status: "indexed",
      visibilityScope: "项目成员",
      updatedAt: "2026-05-31 12:23",
      summary: "覆盖回款新建、合同选择、回款计划同步、金额校验、回款转移、详情查看和财务统计联动。",
      keywords: ["回款", "合同", "回款计划", "回款金额", "统计"],
      difyDatasetId: "ds_superrag_crm_demo",
      difyDocumentId: "crm_payment_doc",
      scene: "handover",
    },
    {
      id: "doc-005",
      title: "05_CRM发票管理模块说明.md",
      type: "Markdown",
      project: "SuperRAG CRM 演示库",
      tags: ["CRM", "发票", "开票申请", "邮寄信息"],
      uploader: "系统预置",
      version: "v1.0",
      status: "indexing",
      visibilityScope: "项目成员",
      updatedAt: "2026-05-31 12:24",
      summary: "覆盖发票申请新建、客户与合同同步、开票金额校验、发票信息、邮寄信息和审批联动。",
      keywords: ["发票", "开票", "合同金额", "邮寄信息", "审批"],
      difyDatasetId: "ds_superrag_crm_demo",
      difyDocumentId: "crm_invoice_doc",
      scene: "design",
    },
  ];

  const mockCitations = [
    {
      id: "cit-001",
      documentTitle: "01_CRM客户管理模块说明.md",
      snippet: "客户转移时，系统需要支持将原负责人移除或转为团队成员，并区分只读权限与读写权限。",
      relevanceScore: 0.94,
      page: 1,
      segmentId: "seg-crm-customer-001",
    },
    {
      id: "cit-002",
      documentTitle: "02_CRM商机管理模块说明.md",
      snippet: "商机金额可由产品价格、数量和折扣自动计算，也可手动录入，但需要记录金额来源。",
      relevanceScore: 0.92,
      page: 1,
      segmentId: "seg-crm-opportunity-002",
    },
    {
      id: "cit-003",
      documentTitle: "03_CRM合同管理模块说明.md",
      snippet: "合同与回款、发票存在强关联，删除合同前必须校验关联数据，防止财务联动被破坏。",
      relevanceScore: 0.91,
      page: 1,
      segmentId: "seg-crm-contract-003",
    },
    {
      id: "cit-004",
      documentTitle: "04_CRM回款管理模块说明.md",
      snippet: "选择回款计划期数后，回款日期和金额应自动同步；当回款金额超过合同金额时，系统应提示确认。",
      relevanceScore: 0.9,
      page: 1,
      segmentId: "seg-crm-payment-004",
    },
    {
      id: "cit-005",
      documentTitle: "05_CRM发票管理模块说明.md",
      snippet: "选择合同后应同步合同金额，开票金额默认取合同金额，但在某些业务场景中可能允许部分开票。",
      relevanceScore: 0.89,
      page: 1,
      segmentId: "seg-crm-invoice-005",
    },
  ];

  const mockSessions = [
    {
      id: "sess-001",
      title: "客户模块有哪些关键业务规则？",
      sceneMode: "chat",
      createdAt: "2026-05-31 12:30",
      updatedAt: "2026-05-31 12:32",
    },
    {
      id: "sess-002",
      title: "CRM 新人应该先读哪些文档？",
      sceneMode: "training",
      createdAt: "2026-05-31 12:10",
      updatedAt: "2026-05-31 12:16",
    },
    {
      id: "sess-003",
      title: "合同到回款的交接风险梳理",
      sceneMode: "handover",
      createdAt: "2026-05-31 11:55",
      updatedAt: "2026-05-31 12:05",
    },
    {
      id: "sess-004",
      title: "生成 CRM 主业务链路设计产物",
      sceneMode: "design",
      createdAt: "2026-05-31 12:18",
      updatedAt: "2026-05-31 12:28",
    },
  ];

  const mockMessages = [
    {
      id: "msg-001",
      sessionId: "sess-001",
      role: "user",
      content: "客户模块有哪些关键业务规则？",
      createdAt: "2026-05-31 12:31",
      citations: [],
    },
    {
      id: "msg-002",
      sessionId: "sess-001",
      role: "assistant",
      content: "客户模块的关键业务规则包括唯一字段校验、负责人和团队成员权限区分、客户转移时的关联数据处理，以及进入公海后的责任切换。",
      createdAt: "2026-05-31 12:32",
      citations: ["cit-001"],
    },
    {
      id: "msg-003",
      sessionId: "sess-002",
      role: "user",
      content: "新人应该先看哪些 CRM 文档？",
      createdAt: "2026-05-31 12:10",
      citations: [],
    },
    {
      id: "msg-004",
      sessionId: "sess-002",
      role: "assistant",
      content: "建议先从客户、商机、合同三份文档开始，再补回款和发票。这样更容易理解 CRM 的完整业务链路：客户 → 商机 → 合同 → 回款 → 发票。",
      createdAt: "2026-05-31 12:16",
      citations: ["cit-001", "cit-002", "cit-003"],
    },
    {
      id: "msg-005",
      sessionId: "sess-003",
      role: "assistant",
      content: "合同到回款的主要交接风险在于合同金额、回款计划和实际回款金额的一致性校验，以及删除或转移操作对财务联动的影响。",
      createdAt: "2026-05-31 12:05",
      citations: ["cit-003", "cit-004"],
    },
  ];

  const mockDesignOutputs = [
    {
      id: "design-001",
      title: "CRM 主业务链路设计产物初稿",
      inputQuestion: "基于当前 CRM 业务文档，生成从客户管理到商机、合同、回款、发票的完整业务流程设计，包括功能清单、详细文本用例、模块划分建议、业务规则、异常场景和设计风险。",
      project: "SuperRAG CRM 演示库",
      outputType: "详细文本用例",
      outputTypeLabel: "详细文本用例",
      granularity: "详细",
      createdAt: "2026-05-31 12:28",
      evidenceLevel: "high",
      functionList: [
        {
          id: "F-001",
          name: "客户资料录入与唯一性校验",
          description: "支持录入客户名称、联系方式、负责人、来源和级别，并按管理员配置执行必填校验和重复客户校验。",
          priority: "高",
          relatedDocument: "01_CRM客户管理模块说明.md",
        },
        {
          id: "F-002",
          name: "商机创建与金额计算",
          description: "创建商机时关联客户和产品，支持基于单价、数量和折扣自动计算商机金额，并跟踪商机阶段流转。",
          priority: "高",
          relatedDocument: "02_CRM商机管理模块说明.md",
        },
        {
          id: "F-003",
          name: "合同生成与客户商机关联",
          description: "合同新建时自动生成合同编号，支持客户、商机、产品和合同金额同步，并为回款和发票提供上游业务对象。",
          priority: "高",
          relatedDocument: "03_CRM合同管理模块说明.md",
        },
        {
          id: "F-004",
          name: "回款计划同步与金额一致性校验",
          description: "根据合同选择回款计划期数后同步回款日期和金额，并校验回款金额与合同金额、计划金额的一致性。",
          priority: "高",
          relatedDocument: "04_CRM回款管理模块说明.md",
        },
        {
          id: "F-005",
          name: "发票申请与合同金额联动",
          description: "新建发票申请时根据客户筛选合同，自动同步合同金额、开票信息和邮寄信息，并校验是否超过合同金额。",
          priority: "高",
          relatedDocument: "05_CRM发票管理模块说明.md",
        },
      ],
      useCases: [
        {
          id: "UC-001",
          name: "新建客户并设置负责人",
          actor: "销售人员",
          preconditions: ["已进入客户管理页面", "客户字段配置已生效"],
          mainSuccessScenario: [
            "销售人员输入客户名称、联系方式、负责人和客户来源",
            "系统校验必填字段和唯一字段规则",
            "系统保存客户，并在列表中展示负责人和客户场景信息",
          ],
          extensionScenarios: ["用户粘贴客户资料后，系统执行 AI 识别辅助录入"],
          exceptionScenarios: ["客户名称或电话重复时，系统提示查重结果并阻止保存"],
          postconditions: "客户资料可被后续商机、合同和交接场景复用。",
        },
        {
          id: "UC-002",
          name: "从商机赢单生成合同并联动回款发票",
          actor: "销售负责人",
          preconditions: ["商机已进入赢单阶段", "合同模块和回款、发票联动规则已配置"],
          mainSuccessScenario: [
            "销售负责人选择赢单商机并创建合同",
            "系统同步客户、产品和商机金额到合同",
            "合同保存后，回款和发票模块可基于合同自动带出金额和客户信息",
          ],
          extensionScenarios: ["无商机关联时，用户手动创建合同并指定客户和产品"],
          exceptionScenarios: ["合同已有关联回款或发票时，系统阻止直接删除合同并提示处理关联数据"],
          postconditions: "合同成为回款与发票联动的统一上游业务对象。",
        },
      ],
      moduleSuggestions: [
        {
          name: "CustomerManagementModule",
          responsibility: "维护客户资料、负责人、团队成员、公海池和跟进记录，是 CRM 主链路的入口模块。",
          input: ["客户基础资料", "负责人", "客户场景配置"],
          output: ["客户档案", "客户视图", "跟进记录"],
          dependencies: ["01_CRM客户管理模块说明.md"],
        },
        {
          name: "OpportunityFlowModule",
          responsibility: "管理商机创建、产品关联、金额计算、阶段流转和赢单输单逻辑。",
          input: ["客户信息", "产品明细", "状态组配置"],
          output: ["商机档案", "阶段记录", "销售漏斗数据"],
          dependencies: ["02_CRM商机管理模块说明.md"],
        },
        {
          name: "ContractFinanceLinkModule",
          responsibility: "负责合同编号生成、商机关联、合同金额同步，并衔接回款和发票模块的财务联动。",
          input: ["客户", "商机", "产品", "合同金额"],
          output: ["合同档案", "回款上游对象", "发票上游对象"],
          dependencies: ["03_CRM合同管理模块说明.md", "04_CRM回款管理模块说明.md", "05_CRM发票管理模块说明.md"],
        },
      ],
      risks: [
        {
          description: "客户转移、公海池和团队成员权限边界复杂，容易出现只读与读写权限混乱。",
          impact: "可能导致客户、商机和合同数据被非负责人误编辑或越权查看。",
          supplement: "补充角色权限矩阵和负责人转移后的关联数据处理规则。",
          confidence: "中",
          needsReview: true,
        },
        {
          description: "商机金额、合同金额、回款金额和开票金额存在多处联动，若同步规则不一致会出现财务口径偏差。",
          impact: "影响销售统计、合同执行和财务核算准确性。",
          supplement: "明确金额来源、同步时机、超额校验和修改日志要求。",
          confidence: "高",
          needsReview: true,
        },
        {
          description: "合同删除、回款删除或发票修改前若未检查关联状态，可能破坏上下游数据完整性。",
          impact: "导致交接时无法准确追踪合同、回款和发票链路。",
          supplement: "在删除和关键字段修改前增加关联数据校验与操作日志。",
          confidence: "高",
          needsReview: true,
        },
      ],
      nextActions: [
        {
          action: "为 CRM 主链路补齐需求-功能-用例-模块追踪矩阵展示",
          priority: "高",
          owner: "前后端共同",
          dependentDocument: "01_CRM客户管理模块说明.md",
          doneDefinition: "页面可直接展示客户、商机、合同、回款、发票的追踪关系和引用证据。",
        },
        {
          action: "补充权限矩阵和负责人转移规则文档",
          priority: "高",
          owner: "产品/后端",
          dependentDocument: "01_CRM客户管理模块说明.md",
          doneDefinition: "客户、商机、合同、回款、发票的负责人、团队成员和管理员权限边界清晰可查。",
        },
        {
          action: "补充金额同步和异常校验说明",
          priority: "高",
          owner: "产品/后端",
          dependentDocument: "02_CRM商机管理模块说明.md",
          doneDefinition: "金额计算、部分开票、超额回款等规则有明确证据支撑。",
        },
      ],
      qualityChecks: {
        hasUncitedContent: false,
        hasRequirementGap: false,
        requiresHumanReview: true,
        readyForReview: false,
      },
      citations: ["cit-001", "cit-002", "cit-003", "cit-004", "cit-005"],
    },
    {
      id: "design-002",
      title: "CRM 权限与财务联动低证据初稿",
      inputQuestion: "请为 CRM 权限边界和合同到回款、发票的财务联动生成接口设计建议。",
      project: "SuperRAG CRM 演示库",
      outputType: "接口设计建议",
      outputTypeLabel: "接口设计建议",
      granularity: "标准",
      createdAt: "2026-05-31 12:26",
      evidenceLevel: "low",
      functionList: [
        {
          id: "F-101",
          name: "权限边界配置接口",
          description: "当前只能初步建议提供负责人、团队成员、管理员的权限配置接口，但缺少字段级权限和审计日志细节。",
          priority: "高",
          relatedDocument: "01_CRM客户管理模块说明.md",
        },
      ],
      useCases: [
        {
          id: "UC-101",
          name: "管理员调整 CRM 权限策略",
          actor: "管理员",
          preconditions: ["管理员已登录", "角色和资源模型待补充"],
          mainSuccessScenario: ["管理员选择角色", "系统展示可管理的客户、商机、合同、回款、发票权限项", "管理员提交权限调整方案"],
          extensionScenarios: ["管理员复制现有角色权限作为模板"],
          exceptionScenarios: ["证据不足时，系统要求人工补充权限矩阵和审计规则"],
          postconditions: "权限策略进入待确认状态。",
        },
      ],
      moduleSuggestions: [
        {
          name: "PermissionAndAuditModule",
          responsibility: "负责权限边界、关键操作审计和财务联动操作日志，但当前缺少完整证据支持。",
          input: ["角色", "资源", "操作动作"],
          output: ["权限草案", "审计日志"],
          dependencies: ["01_CRM客户管理模块说明.md", "03_CRM合同管理模块说明.md"],
        },
      ],
      risks: [
        {
          description: "当前文档对管理员接口、审批流和字段级审计规则覆盖不足。",
          impact: "权限设计和财务联动接口建议不能直接进入开发。",
          supplement: "补充权限矩阵、审批状态机和审计日志字段说明。",
          confidence: "低",
          needsReview: true,
        },
      ],
      nextActions: [
        {
          action: "补充权限矩阵和审计日志文档",
          priority: "高",
          owner: "后端负责人",
          dependentDocument: "01_CRM客户管理模块说明.md",
          doneDefinition: "角色、资源、动作、审批状态和日志字段均有明确文档说明。",
        },
      ],
      qualityChecks: {
        hasUncitedContent: true,
        hasRequirementGap: true,
        requiresHumanReview: true,
        readyForReview: false,
      },
      citations: ["cit-001", "cit-003"],
    },
  ];

  const mockTrainingResult = {
    id: "training-result-001",
    title: "CRM 新人培训说明",
    project: "SuperRAG CRM 演示库",
    topic: "项目背景",
    summary: "当前演示资料围绕 CRM 主业务链路组织为客户、商机、合同、回款、发票五份文档，适合用于演示文档入库、RAG 检索和设计辅助输出。",
    background: "这套 CRM 演示资料比通用系统说明更适合展示“文档证据 → 业务规则 → 结构化设计产物”的价值，因为它天然包含负责人、公海池、阶段流转、金额联动、删除约束和财务关联。",
    terms: [
      {
        term: "客户 → 商机 → 合同 → 回款 → 发票",
        explanation: "CRM 主业务链路，也是当前知识库演示最核心的检索与设计辅助主线。",
      },
      {
        term: "负责人 / 团队成员",
        explanation: "决定客户、商机、合同、回款和发票记录的主要维护责任和可见范围。",
      },
      {
        term: "金额联动",
        explanation: "商机金额、合同金额、回款金额和开票金额之间的同步与一致性校验规则。",
      },
      {
        term: "证据绑定",
        explanation: "所有问答和设计建议都尽量绑定到具体 CRM 文档片段，而不是只返回泛化结论。",
      },
    ],
    learningPath: [
      {
        day: "第 1 天",
        title: "先读客户管理和商机管理",
        description: "理解 CRM 的前半段业务对象、负责人规则、场景筛选和阶段推进。",
      },
      {
        day: "第 2 天",
        title: "阅读合同管理",
        description: "重点理解合同编号、客户商机关联、合同金额同步以及与回款、发票的上游关系。",
      },
      {
        day: "第 3 天",
        title: "阅读回款与发票管理",
        description: "理解财务联动、金额校验、回款计划同步、开票金额和邮寄信息规则。",
      },
      {
        day: "第 4 天",
        title: "测试设计辅助和交接模式",
        description: "尝试生成 CRM 功能清单、详细文本用例、模块划分建议和交接清单。",
      },
      {
        day: "第 5 天",
        title: "关注证据不足与待确认问题",
        description: "观察系统如何把证据不足的地方放入风险或待确认问题，而不是直接编造设计结论。",
      },
    ],
    recommendedDocs: [
      {
        title: "01_CRM客户管理模块说明.md",
        reason: "客户模块定义了负责人、公海池、团队成员、跟进记录等基础业务对象，是 CRM 主链路入口。",
        priority: "高",
        estimatedReadTime: "18 分钟",
      },
      {
        title: "03_CRM合同管理模块说明.md",
        reason: "合同模块是回款与发票的共同上游，最适合演示结构化设计和交接梳理。",
        priority: "高",
        estimatedReadTime: "20 分钟",
      },
      {
        title: "04_CRM回款管理模块说明.md",
        reason: "回款文档非常适合演示金额联动、计划同步和风险提示。",
        priority: "中",
        estimatedReadTime: "15 分钟",
      },
    ],
    citations: ["cit-001", "cit-003", "cit-004"],
  };

  const mockHandoverResult = {
    id: "handover-result-001",
    title: "CRM 业务链路交接摘要",
    project: "SuperRAG CRM 演示库",
    scope: "功能模块",
    projectBackground: "当前演示项目使用 5 份 CRM 业务文档构建知识库，主线覆盖客户、商机、合同、回款和发票，目标是展示知识交接、需求设计辅助和证据追溯能力。",
    currentProgress: "已完成 CRM 五文档演示资料整理，客户、商机、合同、回款、发票主链路已经可以支持结构化设计辅助和交接模式演示。",
    completedFeatures: [
      "客户模块负责人、公海池、团队成员和跟进记录规则已整理入库",
      "商机阶段流转、金额计算和赢单输单规则已形成结构化文档",
      "合同与回款、发票的上下游联动关系已整理完成",
      "回款计划同步、发票金额校验和邮寄信息规则已具备演示材料",
    ],
    unfinishedItems: [
      "权限矩阵、审批流和审计日志字段级规则仍需补充",
      "部分开票、超额回款和合同删除约束还需要更细的异常流程文档",
      "前端页面暂未把追踪矩阵、业务对象、信息缺口全部可视化展示出来",
    ],
    todos: [
      {
        taskName: "补充 CRM 权限矩阵和审计日志文档",
        priority: "高",
        riskLevel: "高",
        owner: "产品/后端",
        dueDate: "2026-06-02",
        status: "待处理",
      },
      {
        taskName: "补充合同删除、回款超额、部分开票等异常流程说明",
        priority: "高",
        riskLevel: "高",
        owner: "产品/后端",
        dueDate: "2026-06-03",
        status: "待确认",
      },
      {
        taskName: "前端增加追踪矩阵、业务规则和信息缺口展示区域",
        priority: "中",
        riskLevel: "中",
        owner: "前端",
        dueDate: "2026-06-04",
        status: "待处理",
      },
    ],
    risks: [
      {
        type: "权限风险",
        description: "客户转移、公海池和团队成员协作已具备基础规则，但字段级权限、管理员动作和审计日志证据仍不足。",
        impact: "影响后续权限设计和正式交接结论的准确性。",
        suggestion: "补充角色权限矩阵、审批流和审计日志文档后再进入正式设计评审。",
        evidenceSource: "01_CRM客户管理模块说明.md",
      },
      {
        type: "金额联动风险",
        description: "商机金额、合同金额、回款金额和开票金额之间存在多处同步关系，若校验规则不统一会造成财务口径偏差。",
        impact: "影响交接后的实现优先级和财务联动设计。",
        suggestion: "补充金额来源、超额校验、部分开票和修改日志规则。",
        evidenceSource: "02_CRM商机管理模块说明.md / 03_CRM合同管理模块说明.md / 04_CRM回款管理模块说明.md / 05_CRM发票管理模块说明.md",
      },
      {
        type: "异常流程缺失",
        description: "删除合同、删除回款、修改开票金额等高风险操作的异常处理细节仍不够完整。",
        impact: "交接时难以直接产出可开发的异常流程设计。",
        suggestion: "优先补充异常场景、限制条件和人工复核规则。",
        evidenceSource: "03_CRM合同管理模块说明.md",
      },
    ],
    roles: [
      {
        role: "产品/业务负责人",
        responsibility: "确认负责人转移、公海池、金额联动、审批流和异常流程规则。",
      },
      {
        role: "后端负责人",
        responsibility: "将 CRM 业务规则落到结构化输出、接口字段和权限校验逻辑中。",
      },
      {
        role: "前端负责人",
        responsibility: "展示结构化设计产物、交接结果、证据追溯和信息缺口提示。",
      },
    ],
    dependentDocs: [
      "docs/crm-demo-docs/01_CRM客户管理模块说明.md",
      "docs/crm-demo-docs/02_CRM商机管理模块说明.md",
      "docs/crm-demo-docs/03_CRM合同管理模块说明.md",
      "docs/crm-demo-docs/04_CRM回款管理模块说明.md",
      "docs/crm-demo-docs/05_CRM发票管理模块说明.md",
    ],
    citations: ["cit-001", "cit-003", "cit-004", "cit-005"],
  };

  const mockHistoryRecords = [
    {
      id: "hist-001",
      title: "CRM 主业务链路设计产物初稿",
      sceneMode: "design",
      project: "SuperRAG CRM 演示库",
      creator: "胡俊熙",
      createdAt: "2026-05-31 12:28",
      summary: "基于 CRM 五文档生成客户、商机、合同、回款、发票主链路的功能清单、文本用例、模块建议和风险提示。",
      originalQuestion: "基于当前 CRM 业务文档，生成从客户管理到商机、合同、回款、发票的完整业务流程设计。",
      outputSummary: "产出 5 个功能项、2 个详细文本用例、3 个模块建议和 3 个核心设计风险。",
      citationCount: 5,
      citations: ["cit-001", "cit-002", "cit-003", "cit-004", "cit-005"],
      versionRecords: [
        {
          version: "v1.0",
          time: "2026-05-31 12:28",
          operator: "胡俊熙",
          change: "生成 CRM 主业务链路设计初稿。",
        },
      ],
    },
    {
      id: "hist-002",
      title: "CRM 新人学习路径",
      sceneMode: "training",
      project: "SuperRAG CRM 演示库",
      creator: "张晨",
      createdAt: "2026-05-31 12:16",
      summary: "围绕客户、商机、合同、回款、发票五份文档生成新人培训说明和阅读顺序。",
      originalQuestion: "CRM 新人应该先读哪些文档？",
      outputSummary: "建议按客户 → 商机 → 合同 → 回款 → 发票的顺序理解业务链路。",
      citationCount: 3,
      citations: ["cit-001", "cit-003", "cit-004"],
      versionRecords: [
        {
          version: "v1.0",
          time: "2026-05-31 12:16",
          operator: "张晨",
          change: "生成 CRM 新人培训说明。",
        },
      ],
    },
    {
      id: "hist-003",
      title: "合同到回款交接风险梳理",
      sceneMode: "handover",
      project: "SuperRAG CRM 演示库",
      creator: "徐涛涛",
      createdAt: "2026-05-31 12:05",
      summary: "围绕合同金额、回款计划、实际回款和发票金额校验梳理 CRM 财务联动交接风险。",
      originalQuestion: "请生成合同到回款的交接清单，并指出最大风险。",
      outputSummary: "重点指出金额联动、权限边界和异常流程缺失三类风险，并生成待办清单。",
      citationCount: 4,
      citations: ["cit-003", "cit-004", "cit-005", "cit-001"],
      versionRecords: [
        {
          version: "v1.0",
          time: "2026-05-31 12:05",
          operator: "徐涛涛",
          change: "生成 CRM 交接摘要。",
        },
      ],
    },
    {
      id: "hist-004",
      title: "客户模块业务规则问答",
      sceneMode: "chat",
      project: "SuperRAG CRM 演示库",
      creator: "胡俊熙",
      createdAt: "2026-05-31 12:32",
      summary: "说明客户唯一性校验、负责人与团队成员权限、公海池规则和客户转移约束。",
      originalQuestion: "客户模块有哪些关键业务规则？",
      outputSummary: "回答强调唯一字段、负责人、团队成员、公海池和关联数据转移规则。",
      citationCount: 1,
      citations: ["cit-001"],
      versionRecords: [
        {
          version: "v1.0",
          time: "2026-05-31 12:32",
          operator: "胡俊熙",
          change: "生成 CRM 业务规则问答结果。",
        },
      ],
    },
  ];

  const mockWorkflows = [
    {
      sceneCode: "chat",
      sceneName: "通用问答 Workflow",
      difyAppId: "app_general_chat",
      difyWorkflowId: "wf_general_chat_v1.2",
      status: "enabled",
    },
    {
      sceneCode: "training",
      sceneName: "培训模式",
      difyAppId: "app_training_mode",
      difyWorkflowId: "wf_training_mode_v1.2",
      status: "enabled",
    },
    {
      sceneCode: "handover",
      sceneName: "交接模式",
      difyAppId: "app_handover_mode",
      difyWorkflowId: "wf_handoff_mode_v1.1",
      status: "enabled",
    },
    {
      sceneCode: "design",
      sceneName: "设计辅助",
      difyAppId: "app_design_assistant",
      difyWorkflowId: "wf_design_assist_v1.3",
      status: "enabled",
    },
    {
      sceneCode: "document-summary",
      sceneName: "文档解析摘要 Workflow",
      difyAppId: "app_document_summary",
      difyWorkflowId: "wf_document_summary_v1.0",
      status: "enabled",
    },
    {
      sceneCode: "low-evidence",
      sceneName: "证据不足提示 Workflow",
      difyAppId: "app_low_evidence",
      difyWorkflowId: "wf_low_evidence_v1.0",
      status: "disabled",
    },
  ];

  const mockSettings = {
    retrieval: {
      topK: 8,
      scoreThreshold: 0.35,
      rerankEnabled: true,
      knowledgeStrategy: "hybrid",
      lowEvidenceHintEnabled: true,
    },
    model: {
      modelName: "qwen-max",
      temperature: 0.3,
      maxTokens: 2048,
      streamOutput: true,
    },
  };

  const mockLogs = [
    {
      id: "log-001",
      time: "2026-05-31 12:28",
      user: "胡俊熙",
      sceneMode: "design",
      workflow: "wf_design_assist_v1.3",
      success: true,
      durationMs: 7640,
      errorReason: "",
    },
    {
      id: "log-002",
      time: "2026-05-31 12:32",
      user: "胡俊熙",
      sceneMode: "chat",
      workflow: "wf_general_chat_v1.2",
      success: true,
      durationMs: 2140,
      errorReason: "",
    },
    {
      id: "log-003",
      time: "2026-05-31 12:16",
      user: "张晨",
      sceneMode: "training",
      workflow: "wf_training_mode_v1.2",
      success: true,
      durationMs: 4260,
      errorReason: "",
    },
    {
      id: "log-004",
      time: "2026-05-31 12:05",
      user: "徐涛涛",
      sceneMode: "handover",
      workflow: "wf_handoff_mode_v1.1",
      success: true,
      durationMs: 5980,
      errorReason: "",
    },
  ];

  window.SuperRagMock = {
    mockStats,
    mockDocuments,
    mockSessions,
    mockMessages,
    mockCitations,
    mockTrainingResult,
    mockHandoverResult,
    mockDesignOutputs,
    mockHistoryRecords,
    mockWorkflows,
    mockSettings,
    mockLogs,
  };
})();
